# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json (if available)
COPY package.json ./

# Install the dependencies
RUN --mount=type=cache,target=/root/.npm npm install

# Copy the current directory contents into the container at /app
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a smaller Node.js runtime for the final image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy only the build directory and package.json into the final image
COPY --from=builder /app/build ./build
COPY package.json .

# Install only the production dependencies
RUN npm ci --omit=dev

# Environment variables for the Twitch API
ENV TWITCH_CLIENT_ID=your_client_id
ENV TWITCH_CLIENT_SECRET=your_client_secret

# Run the application
ENTRYPOINT ["node", "build/index.js"]
